Tugas_2_PPW_C_14/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import app_profile.urls as profile
import app_dashboard.urls as dashboard
import fitur_forum.urls as forum
import app_response.urls as response

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/',include(profile,namespace="profile")),
    url(r'^dashboard/', include(dashboard, namespace="dashboard")),
    url(r'^forum/',include(forum,namespace="forum")),
    url(r'^response/',include(response,namespace="response")),
    url(r'^$', RedirectView.as_view(url="/dashboard/",permanent="false"),name='dashboard'),
]

app_dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),

]

app_profile/urls.py
from django.conf.urls import url
from .views import index,get_data
#url for app
urlpatterns = [
    url(r'^$', index, name='profile'),
    url(r'^get_data/',get_data,name="get_data")
]

app_response/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
    ]

fitur_forum/urls.py
from django.conf.urls import url
from .views import index, add_message, dashboard
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_message/(?P<id>.*)/$', add_message, name='add_message'),
	url(r'^dashboard/$', dashboard, name='dashboard'),

	# custom auth
	url(r'^custom_auth/login/$', auth_login, name='auth_login'),
	url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]
       
    

app_profile/models.py
from django.db import models

# Create your models here.

app_response/models.py
from django.db import models
from fitur_forum.models import Message

fitur_forum/models.py
from django.db import models

# Create your models here.
class Pengguna(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Message(models.Model):
	pengguna = models.ForeignKey(Pengguna)
	title = models.CharField(max_length=140)
	message = models.TextField()
	kode_message = models.CharField("Kode Message", max_length=50)
	created_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
	pengguna = models.ForeignKey(Pengguna)
	message = models.ForeignKey(Message)
	comment = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

    

app_response/forms.py
from django import forms

class comment_form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    attrs = {
        'class': 'form-control'
    }
    post = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

fitur_forum/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    title_attrs = {
        'class': 'form-control',
        'placeholder':'This post is about...'
    }

    message_attrs = {
        'class': 'form-control',
        'placeholder':'Your post is...'
    }

    title = forms.CharField(label='Judul Forum', required=True, max_length=30, widget=forms.TextInput(attrs=title_attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=message_attrs), required=True)

app_dashboard/views.py
from django.shortcuts import render

response = {}

def index(request):
	html = 'dashboard/dashboard.html'
	return render(request, html, response)

app_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
response = {}

def index(request):
    if('id' in request.session):
        try:
            response['name'] = request.session.get('name')
            response['type'] = request.session.get('type')
            if(response['name']==None and response['type']==None):
                raise KeyError
        except KeyError:
            get_data(request)

        return render(request, 'profile.html', response)
    else:
        return HttpResponseRedirect('/dashboard/')

@csrf_exempt
def get_data(request):
    request.session['name'] = request.POST.get('name')
    request.session['type'] = request.POST.get('type')
    return HttpResponseRedirect('/profile/')

app_response/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect


response = {}

def index(request):
	response['Comment'] = Comment
	html = 'app_response/app_response.html'
	forum = Forum.objects.all()
	response['forum'] = forum
	return render(request, html, response)
    
def add_response(request):
	form = CommentForm(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['comment'] = request.POST.get('comment')
		response['id'] = request.POST.get('data.id')
		obj = Forum.objects.get(pk=response['id'])
		comment = Comment(response['comment'])
		comment.save()
		return HttpResponseRedirect('/menanggapi/')

fitur_forum/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Message_Form
from .models import Message
from .utils import *

# Create your views here.
response = {}
def index(request):
    # print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('forum:dashboard'))
    else:
        response['author'] = get_data_user(request, 'user_login')
        html = 'fitur_forum/login.html'
        return render(request, html, response)

def dashboard(request):
    
    if not 'user_login' in request.session.keys():
        return HttpResponseRedirect(reverse('forum:index'))
    else:
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            pengguna = create_new_user(request)

        message = Message.objects.filter(pengguna=pengguna)
        
        response['message'] = message
        response['message_form'] = Message_Form
        response["message_list"] = message
        html = 'fitur_forum/fitur_forum.html'
        
        message_list = message
        paginator = Paginator(message_list, 5)
        page = request.GET.get('page', 1)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)
       
        response["message_list"] = users
        html = 'fitur_forum/fitur_forum.html'
        return render(request, html, response)

def add_message(request, id):
    response['id'] = id
    form = Message_Form(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            pengguna = create_new_user(request)  
     
        response['title'] = request.POST['title'] 
        response['message'] = request.POST['message']
        message = Message(pengguna=pengguna,title=response['title'], message=response['message'], kode_message = id)
        message.save()
        response['id'] = id
        html ='fitur_forum/fitur_forum.html'    
        return HttpResponseRedirect('/forum/')

def paginate_page(page, data_list):
    paginator = Paginator(data_list, 5)

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = data.number - 1
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 10, so lets calculate where to slice the list
    start_index = index if index >= 5 else 0
    end_index = 5 if index < max_index - 5 else max_index
    # Get our new page range. In the latest versions of Django page_range returns 
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data':data, 'page_range':page_range}
    return paginate_data

app_dashboard/templates/dashboard/dashboard.html
{% load staticfiles %}
{% load static %}

<head>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<script type="text/javascript" src="//platform.linkedin.com/in.js">
		api_key: 81q5awfazmzhge
		authorize: true
		onLoad: onLinkedInLoad
	</script>

	<script type="text/javascript">
		function companyLogin(company) {
			window.location.href = "/company/" + company.id + "/";
		}
	</script>
	
	<script src="{% static 'js/dashboard.js' %}"></script>

</head>

<title>BukaLaptop</title>

<header>
</header>

<div style="text-align: center; background-color: white">
	<h1 style="font-family: 'Shadows Into Light', cursive; color: #31708f;">
		Cari Kerja ?
		<br>
		BukaLaptop aja
		<br>
		#GaNganggur
	</h1>

	<br>

	<script type="in/Login"></script> <br>
</div>

app_profile/templates/profile.html
{% load staticfiles %}
{% load static %}

<html>
  <head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur2.css' %}" />    

    <script type="text/javascript" src="{% static 'js/fitur2.js' %}"></script>
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
      api_key: 81q5awfazmzhge
      authorize: true
      onLoad: onLinkedInLoad
    </script>
    <title>Profile Perusahaan</title>
  </head>
  <body>
    <section style="height: auto;">
      <header class="masthead">
        <div class="overlay">
          <div class="container">
            <h1 class="display-1 text-white">WELCOME {{ name }} </h1>
            <img class="img-responsive center-block" src=http://cliparting.com/wp-content/uploads/2016/11/Small-office-building-clipart-kid.jpg width="300" height="300">
            <a href="#" class="head-button"><center>Lihat Forum</center></a>
            <a href="#" class="head-button"><center>Cari Mahasiswa</center></a>
          </div>
        </div>
      </header>

      <div class="container" style="margin-top: 4%;" id="about-company-section">
        <div class="row">
          <div class="col-lg-11 col-md-11 col-sm-11 col-11 mx-auto">
            <h2 id="title-about">About Company:</h2>
            <div id="about"></div>
            <br>
            <div class="row">
              <div class="col-lg-6 col-md-4 col-sm-4 col-4" id="judul-about">
                <h5 id="about-company">Tipe Perusahaan</h5>
                <h5 id="about-company">Web Perusahaan</h5>
                <h5 id="about-company">Spesialitas</h5>
              </div>
              <div class="col-lg-6 col-md-8 col-sm-4 col-8">
                <h5 id="companyType"> {{ type }}</h5>
                <h5 id="companyWeb"> google.com</h5>
                <!-- : <a href="https://{{companyWeb}}">{{companyWeb}}<a> -->
                <h5 id="companySpecialty">Web Berbasis Zakat</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app_response/templates/app_response.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container">
	<style>
		img {
			float:left
		}
	</style>
	<body id="forum">
	{% for data in forum reversed %}
		<img src="https://forum.tudiabetes.org/uploads/default/original/3X/3/5/35d47232d1d9cb26dcd2a226952f98137a9080c8.jpg" width=50px height=50px></img>
		<p id="postingan">{{data.content}}</p>
		<h5 id="tanggal">{{data.created_date}}</h5>
		<form id="form" method="POST" action="{% url 'menanggapi:tambah_tanggapan' %}">
			{% csrf_token %}
			{{ CommentForm }}
			<br>
            <button type="Post" class="btn btn-default">Post</button>
        </form>
		<hr>
	{%endfor%}
	</body>
</div>
{% endblock %}

fitur_forum/templates/fitur_forum/dashboard.html
{% extends "lab_10/layout/base.html" %}

{% block header %}
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">IQBAL</a>
    </div>
    
    


  </div><!-- /.container-fluid -->
</nav>  
{% endblock %}

{% block content %}
<!-- Content Here -->
<section id="data-dashboard">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2> Dashboard </h2>
        </div>
        <div class="panel-body">
            <p> Username : {{ author }} </p>
            <p> NPM : {{kode_identitas}} </p>
            <p> Role : {{ role }} </p>
            <p>
                <a href="{% url 'lab-10:movie_list' %}" class="btn btn-primary"> Daftar Movie </a>
                <a href="{% url 'lab-10:list_watch_later' %}" class="btn btn-warning"> Daftar Watch Later </a>
            </p>
        </div>
    </div>
</section>
<hr>

{% endblock %}

fitur_forum/templates/fitur_forum/fitur_forum.html
{% extends "fitur_forum/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block header %}
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">IQBAL</a>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <a href="{% url 'forum:auth_logout' %}" class="btn btn-danger navbar-btn" onclick="return confirm('Keluar?')">Logout </a>  
      </ul>
      
    </div>


  </div><!-- /.container-fluid -->
</nav>  
{% endblock %}

{% block content %}


<section name="form">
    <h2>Send Message</h2>
    <form id="form" method="POST" action="{% url 'forum:add_message' id %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>
<div class="list-group">
{% if message_list %}
         
        {% for i in message_list %}
        <a class="list-group-item clearfix"> 
            {{i.title}} - {{i.message}} - {{i.created_date}} 
        </a>        
        {% endfor %}
  
{% else %}
    <button type="submit" class="btn btn-primary btn-lg btn-block no-friend">You have no discussion.</button>
{% endif %}
</div>

{% if message_list.has_other_pages %}
    <ul class="pagination">
        {% if message_list.has_previous %}
            <li><a href="?page={{ message_list.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in message_list.paginator.page_range %}
            {% if message_list.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if message_list.has_next %}
              <li><a href="?page={{ message_list.next_page_number }}">&raquo;</a></li>
        {% else %}
              <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}
{% endblock %}

fitur_forum/templates/fitur_forum/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                      {% if mahasiswa_list.has_other_pages %}
                        <ul class="pagination">
                            {% if mahasiswa_list.has_previous %}
                                <li><a href="?page={{ mahasiswa_list.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}

                            {% for i in mahasiswa_list.paginator.page_range %}
                                {% if mahasiswa_list.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if mahasiswa_list.has_next %}
                                  <li><a href="?page={{ mahasiswa_list.next_page_number }}">&raquo;</a></li>
                            {% else %}
                                  <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}

                </div>
                {% if auth %}
                    <div id="token" hidden="true">{{ auth.access_token }}</div>
                    <div id="cid" hidden="true">{{ auth.client_id }}</div>
                {% endif %}
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">NPM</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">Nama</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            success : function (friend) {
                list_friend = $.parseJSON(friend);
                console.log(list_friend.friend_name);
                html = '<a class="list-group-item clearfix">' +
                    list_friend.friend_name + " (" + list_friend.npm + ")"
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
        var npm = $("#field_npm").val();
        var corsProxy = 'https://cors-anywhere.herokuapp.com/';
        var obj = new Object(); obj.access_token = token; obj.client_id = cid;
        var param = $.param(obj);

        $.ajax({
            method: "GET",
            url: corsProxy+'https://api-dev.cs.ui.ac.id/siakngcs/mahasiswa/'+npm+'/?'+param,
            success: function(data) {
                addFriend(data.nama, data.npm
                )
            },
            error: function(error) {
                console.log(error)
                alert("\n\t\t\tNPM tidak valid:\n\n'Tidak ada mahasiswa dengan NPM tersebut'")
            }
        });
        event.preventDefault();

    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}

fitur_forum/templates/fitur_forum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 10">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">   
     <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/lab_10.css' %}"> -->

    
    <title>
        {% block title %} Forum Perusahaan {% endblock %}
    </title>
</head>
<body>
<header>
    {% block header %}
    <!-- Your Header Here -->
    {% endblock %}
</header>
<content>

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}

    <h1 style="text-align:center">
        <small><em><p style="text-align: center">&copy; Muhammad Iqbal Mahendra</p> </em></small>
    </h1>
    <!-- Your Footer Here -->
    {% endblock %}
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>

</body>
</html>

fitur_forum/templates/fitur_forum/login.html
{% extends "fitur_forum/layout/base.html" %}

{% block header %}
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">IQBAL</a>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
      </ul>
      
    </div>


  </div><!-- /.container-fluid -->
</nav>  
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'forum:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

fitur_forum/templates/fitur_forum/partials/header.html
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">IQBAL</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'lab-9:auth_logout' %}" onclick="return confirm('Keluar?')">Logout</a></li>
        <li> <a href="{% url 'lab-9:cookie_login' %}"> Masuk Halaman Cookies </a></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>